MonsterTest/Models/Group.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MonsterTest.Models
{
	public class Group
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public int SupplierId { get; set; }
		public Supplier Supplier { get; set; }
	}
}

MonsterTest/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;

namespace MonsterTest.Models
{
	public class Supplier
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Address { get; set; }
		public string Email { get; set; }
		public string Phone { get; set; }

		public List<Group> Groups { get; set; }
	}
}

MonsterTest/ViewModels/SupplierViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonsterTest.ViewModels
{
	public class SupplierViewModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Address { get; set; }

		[EmailAddress]
		public string Email { get; set; }
		public string Phone { get; set; }
		public IEnumerable<SelectListItem> SelectedGroups { get; set; }
	}
}

MonsterTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonsterTest.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

MonsterTest/Controllers/SupplierController.cs
using MonsterTest.Models;
using MonsterTest.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections.ObjectModel;
using MonsterTest.Services;
using MonsterTest.ViewModels;
using System.Web.Services;

namespace MonsterTest.Controllers
{
	public class SupplierController : Controller
	{
		public SupplierController()
		{
			_supplierRepository = SupplierRepository.Instance;
			HttpSession.SessionSuppliers = _supplierRepository.Get();
		}
		private SupplierRepository _supplierRepository;

		public ActionResult List()
		{
			if (HttpSession.SessionSuppliers == null)
				HttpSession.SessionSuppliers = _supplierRepository.Get();
			return View(HttpSession.SessionSuppliers);
		}

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(SupplierViewModel model)
		{
			try
			{
				Supplier supplier = new Supplier();
				supplier.Id = HttpSession.SessionSuppliers.Select(a => a.Id).Max() + 1;
				supplier.Name = model.Name;
				supplier.Address = model.Address;
				supplier.Email = model.Email;
				supplier.Phone = model.Phone;

				List<Group> groups = new List<Group>();
				foreach (var group in model.SelectedGroups)
				{
					groups.Add(new Group() { Id = Convert.ToInt32(group.Value), Name = group.Text });
				}
				supplier.Groups = groups;

				HttpSession.SessionSuppliers.Add(supplier);
				return RedirectToAction("List");
			}
			catch
			{
				return View(model);
			}
		}

		public ActionResult Edit(int id)
		{
			var supplier = _supplierRepository.Get().Where(a => a.Id == id).FirstOrDefault();
			SupplierViewModel model = new SupplierViewModel();
			model.Id = supplier.Id;
			model.Name = supplier.Name;
			model.Email = supplier.Email;
			model.Address = supplier.Address;
			model.Phone = supplier.Phone;
			List<SelectListItem> selectedGroups = new List<SelectListItem>();
			foreach (var group in supplier.Groups)
			{
				selectedGroups.Add(new SelectListItem() { Text = group.Name, Value = group.Id.ToString(), Selected = true });
			}
			model.SelectedGroups = selectedGroups;
			return View(model);
		}

		[HttpPost]
		public ActionResult Edit(int id, SupplierViewModel supplier)
		{
			try
			{
				var original = HttpSession.SessionSuppliers.Where(a => a.Id == id).FirstOrDefault();
				original.Name = supplier.Name;
				original.Address = supplier.Address;
				original.Email = supplier.Email;
				original.Phone = supplier.Phone;
				List<Group> groups = new List<Group>();
				foreach (var group in supplier.SelectedGroups)
				{
					groups.Add(GroupRepository.Instance.Get().Where(a => a.Id == Convert.ToInt32(group.Value)).FirstOrDefault());
				}
				original.Groups = groups;

				return RedirectToAction("List");
			}
			catch (Exception ex)
			{
				return View(supplier);
			}
		}

		public ActionResult Delete(int id)
		{
			if (HttpSession.SessionSuppliers != null)
			{
				Supplier supplier = HttpSession.SessionSuppliers.Where(a => a.Id == id).FirstOrDefault();
				HttpSession.SessionSuppliers.Remove(supplier);
				return RedirectToAction("List");
			}
			return View("List");
		}
		[HttpPost]
		public ActionResult ValidateEmail(string email)
		{
			if (HttpSession.SessionSuppliers != null)
				return Json(HttpSession.SessionSuppliers.Where(a => a.Email == email).Any());
			return Json(_supplierRepository.Get().Where(a => a.Email == email).Any());
		}
	}
}

MonsterTest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MonsterTest/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MonsterTest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MonsterTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	<script src="~/Scripts/Main.js"></script>
</head>
<body>
	<div class="menu-bar">
		<ul>
			<li>
				@Html.ActionLink("MONSTER", "List", "Supplier")
			</li>
		</ul>
	</div>
	@*<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li>@Html.ActionLink("Monster suppliers", "List", "Supplier")</li>
					</ul>
				</div>
			</div>
		</div>*@
	<div class="container body-content">
		@RenderBody()
		<hr />
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>

MonsterTest/Views/Supplier/Create.cshtml
@model MonsterTest.ViewModels.SupplierViewModel
@using MonsterTest.Services

@{
	ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Supplier</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @id = "email" } })
				@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.SelectedGroups, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.ListBoxFor(model => model.SelectedGroups, ViewDataService.GetGroups(), new { htmlAttributes = new { @class = "form-control", @multiple = "multiple" } })
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
	<script type="text/javascript">
		$("#email").change(function () {
			$.ajax({
				type: "POST",
				url: "/Supplier/ValidateEmail",
				data: { email: $('#email').val() },
				dataType: "json",
				success: function (msg) {
					var message = JSON.parse(msg);
					if (message == true) {
						alert('email already exists');
					}
				}
			});
		});
	</script>
}

MonsterTest/Views/Supplier/Edit.cshtml
@model MonsterTest.ViewModels.SupplierViewModel
@using MonsterTest.Services

@{
	ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Supplier</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.Id)

		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.SelectedGroups, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.ListBoxFor(model => model.SelectedGroups, ViewDataService.GetGroups(), new { htmlAttributes = new { @class = "form-control", @multiple = "multiple" } })
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

MonsterTest/Views/Supplier/List.cshtml
@model IEnumerable<MonsterTest.Models.Supplier>

@{
   
	ViewBag.Title = "Suppliers";
}

<h2>@ViewBag.Title</h2>

<p>
	@Html.ActionLink("Create New", "Create",new { htmlAttributes = new { @class = "btn btn-default" } })
</p>
<table class="table table-bordered table-hover">
	<tr class="table-heading">
		<th>
			@Html.DisplayNameFor(model => model.Name)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Address)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Email)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Phone)
		</th>
		<th>@Html.DisplayNameFor(a => a.Groups)</th>
		<th>Actions</th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Name)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Address)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Email)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Phone)
			</td>
			<td>
				@{
					foreach (var group in item.Groups)
					{
						if (group != null)
						{
							<span>@group.Name</span><br />
						}
					}
				}
			</td>
			<td>
				@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
				@Html.ActionLink("Delete", "Delete", new { id = item.Id })
			</td>
		</tr>
					}

</table>